[package]
name = "rust_nes_emu"
version = "0.1.0"
authors = ["ozborne132 <ozborne132@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4.0"